import type { Metadata } from 'next'

import { cn } from '@functions/classNames'
import { Poppins } from 'next/font/google'
import './globals.css'

const poppins = Poppins({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Retro App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={cn('min-h-screen w-screen bg-[#f7fafd]', poppins.className)}>
        {children}
      </body>
    </html>
  )
}
